Spec doesn't mention String as a built-in converter
eclipse/microprofile-config pull request #679
Opened 2021-03-12 16:19 UTC by tevans78

Spec doesn't mention String as a built-in converter ... the Converter JavaDoc does
https://github.com/eclipse/microprofile-config/blob/4bda7c776e00a3baf41af728215900e02485de2c/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L70

2021-03-12 19:15 UTC, radcortez commented
Hi @tevans78 . Thanks!

Can you include the "Signed-off-by" footer: https://accounts.eclipse.org/legal/eca/validation/62168? We can't merge without it.

2021-03-12 21:34 UTC, Emily-Jiang commented
`String` is an automatic converter as it has a public constructor taking a string parameter. The spec does not mention String as a default convertor either. Therefore, I don't think any changes are needed here.

2021-03-12 21:35 UTC, Emily-Jiang requested changes

2021-03-12 21:35 UTC, Emily-Jiang commented on spec/src/main/asciidoc/converters.asciidoc
> +* `java.lang.String`
It is an automatic converter. No need to be mentioned here. I think the javadoc needs to be updated to have that line removed instead.

2021-03-15 10:08 UTC, tevans78 commented
@radcortez The signoff is missing because I used the github.com web UI to create the PR automatically.
Since @Emily-Jiang thinks the change is not the right one anyway, I think I will close this PR and create an issue instead.

2021-03-15 10:08 UTC, closed without merging